name: Manual Deploy Trigger
on:
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Trigger
        id: render-deployer
        uses: OneHox/render-deploy-api@v1.0.0
        with:
          serviceId: ${{ secrets.RENDER_APP_SERVICE_ID }}
          bearer: ${{ secrets.RENDER_PROFILE_AUTH_API_TOKEN }}
      - name: Message
        run: echo "${{ steps.render-deployer.outputs.response }}"
