name: Prod
env: { PORT: 8080, Group: Prod }
on:
  workflow_dispatch:
  pull_request:
    branches: [stage]
    types: [closed]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
